

name: open VPN

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'this a test'
        required: true
        default: 'TEST'
        type: choice
        options:
        - 'TEST'
        - 'TEST2'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install playwright Browsers
      run: npx playwright install --with-deps
    - name: Install open vpn 
      run: |
          sudo apt-get update
          sudo apt-get --assume-yes --no-install-recommends install openvpn      
    - name: Connect openvpn 
      run: sudo openvpn --config "./node-jp-25.protonvpn.net.udp.ovpn" --log "vpn.log" --daemon 
    - name: Run playwright test
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1

