

name: Proton VPN

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'this a test'
        required: true
        default: 'TEST'
        type: choice
        options:
        - 'TEST'
        - 'TEST2'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: download proton vpn repo
      run: curl -O https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
    - name: install proton vpn repo
      run:  sudo apt-get install ./protonvpn-stable-release_1.0.3_all.deb
    - name: update aptget
      run:  sudo apt-get update
    - name: install proton vpn
      run:  sudo apt-get install protonvpn-cli 
    - name: login to proton vpn
      run:  protonvpn-cli login pon.tu.correo.aca@gmail.com
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install playwright Browsers
      run: npx playwright install --with-deps
    - name: Run playwright test
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retantion-days: 1

