


name: Reporting

on:
  workflow_call:
    inputs:
      test:
        description: 'this a test'
        required: false
        default: 'TEST'
        type: string
        
jobs:
  reports:
    if: always()
    timeout-minutes: 10
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Print Type
      run: echo ${{ inputs.test }}

    - name: Print test
      run: echo "Test"

    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from Github actions 
      uses: actions/download-artifact@v3
      with:
        name: all-blob-reports
        path: all-blob-reports

    - name: Merge into HTML report
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: html-report-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 1
    
    - name: Merge into XML report
      run: PLAYWRIGHT_JUNIT_OUTPUT_NAME='playwright-junit-report/results.xml' npx playwright merge-reports --reporter junit ./all-blob-reports

    - name: Upload JUnit Report
      uses: actions/upload-artifact@v3
      with:
        name: junit-report-${{ github.run_attempt }}
        path: playwright-junit-report
        retention-days: 1

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      if: always()
      with:
        path: playwright-report/
    
    - name: Deploy to GitHub Pages
      id: deployment
      if: always()
      uses: actions/deploy-pages@v2
