name: test worflow

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project/Environment to run tests on'
        required: true
        default: 'STAGING'
        type: choice
        options:
          - 'STAGING'
          - 'PROD'
          - 'PLASMIC'
          - 'DEVELOP'
          - 'STAGING_BRAZIL'
          - 'PROD_BRAZIL'
      freeUsers:
        description: 'Create Free users'
        required: false
        default: false
        type: boolean
      monthlyUsers:
        description: 'Create Monthly users'
        required: false
        default: false
        type: boolean
      annualUsers:
        description: 'Create Annual users'
        required: false
        default: false
        type: boolean
      startIndex:
        description: 'Starting list index'
        required: true
        type: number
      userCount:
        description: 'number of users to create'
        required: true
        type: number

jobs:
  generate_parameters:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      tags: ${{ steps.set_tags.outputs.tags }}
    steps:
      - name: generate matrix
        id: set_matrix
        run: |
          n=${{ github.event.inputs.userCount }}
          matrix="{\"matrix\":["
          for ((i=1; i<=n; i++)); do
            matrix+="\"$i/$n\""
            if [[ $i -lt $n ]]; then
              matrix+=","
            fi
          done
          matrix+="]}"
          echo "matrix=${matrix}" 
          echo "matrix=${matrix}" >> $GITHUB_OUTPUT
      - name: generate tags
        id: set_tags
        run: |
          free=${{ github.event.inputs.freeUsers }}
          monthly=${{ github.event.inputs.monthlyUsers }}
          annual=${{ github.event.inputs.annualUsers }}

          list=()
          if [[ $free == 'true' ]]; then
            list+=("'free'")
          fi
          
          if [[ $monthly == 'true' ]]; then
            list+=("'monthly'")
          fi
          
          if [[ $annual == 'true' ]]; then
            list+=("'annual'")
          fi
          
          tags="\""
          array_length=${#list[@]}
          
          echo $array_length
           for ((i=0; i<=$array_length; i++)); do
              tags+="${list[i]}"
             if [[ $i -lt  $((array_length-1)) ]]; then
              tags+="|"
             fi
           done
          tags+="\""
           
          echo "tags=${tags}"
          echo "tags=${list[@]}" >> $GITHUB_OUTPUT
  test:
    needs: generate_parameters
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        shard: ${{fromJson(needs.generate_parameters.outputs.matrix)['matrix']}}
    steps:
      - name: print tags
        run: echo "${{needs.generate_parameters.outputs.tags}}"
      - name: print matrix 1
        run: echo "${{needs.generate_parameters.outputs.matrix}}"
      - name: print matrix 2
        run: echo "${{fromJson(needs.generate_parameters.outputs.matrix)['matrix']}}"
      - name: print shard
        run: echo "${{matrix.shard}}"

